// Road Trip Explorer — item pool
// regions: 'any' = available everywhere. Otherwise one or more of:
// 'desert', 'coastal', 'mountains', 'farmland', 'forest', 'urban'
// points: 1 = common, 3 = uncommon, 5 = rare / bonus

const ITEMS = [
  // ---- Vehicles & Transportation ----
  { id: 'pickup-truck', emoji: '🛻', label: 'Pickup truck', points: 1, regions: ['any'], category: 'Vehicles' },
  { id: 'motorcycle', emoji: '🏍️', label: 'Motorcycle', points: 1, regions: ['any'], category: 'Vehicles' },
  { id: 'school-bus', emoji: '🚌', label: 'School bus', points: 1, regions: ['any'], category: 'Vehicles' },
  { id: 'semi-truck', emoji: '🚚', label: 'Semi-truck / big rig', points: 1, regions: ['any'], category: 'Vehicles' },
  { id: 'police-car', emoji: '🚓', label: 'Police car', points: 3, regions: ['any'], category: 'Vehicles' },
  { id: 'fire-truck', emoji: '🚒', label: 'Fire truck', points: 3, regions: ['any'], category: 'Vehicles' },
  { id: 'convertible', emoji: '🚗', label: 'Convertible, top down', points: 3, regions: ['any'], category: 'Vehicles' },
  { id: 'boat-trailer', emoji: '🚤', label: 'Boat on a trailer', points: 3, regions: ['any'], category: 'Vehicles' },
  { id: 'hot-air-balloon', emoji: '🎈', label: 'Hot air balloon', points: 5, regions: ['any'], category: 'Vehicles', fact: 'Hot air balloons float because the hot air inside is lighter than the air outside!' },
  { id: 'train', emoji: '🚂', label: 'Train', points: 3, regions: ['any'], category: 'Vehicles' },
  { id: 'helicopter', emoji: '🚁', label: 'Helicopter', points: 5, regions: ['any'], category: 'Vehicles' },
  { id: 'rv-camper', emoji: '🚐', label: 'RV or camper van', points: 3, regions: ['any'], category: 'Vehicles', fact: 'Some RVs are as long as a school bus and have their own kitchens!' },
  { id: 'tractor', emoji: '🚜', label: 'Tractor', points: 1, regions: ['farmland'], category: 'Vehicles' },
  { id: 'food-truck', emoji: '🌮', label: 'Food truck', points: 3, regions: ['urban'], category: 'Vehicles' },
  { id: 'taxi', emoji: '🚕', label: 'Taxi cab', points: 1, regions: ['urban'], category: 'Vehicles' },
  { id: 'subway-entrance', emoji: '🚇', label: 'Subway / metro entrance', points: 3, regions: ['urban'], category: 'Vehicles' },

  // ---- Animals ----
  { id: 'cow', emoji: '🐄', label: 'Cow', points: 1, regions: ['any', 'farmland'], category: 'Animals' },
  { id: 'horse', emoji: '🐴', label: 'Horse', points: 1, regions: ['any', 'farmland'], category: 'Animals' },
  { id: 'goat', emoji: '🐐', label: 'Goat', points: 3, regions: ['farmland', 'mountains'], category: 'Animals' },
  { id: 'sheep', emoji: '🐑', label: 'Sheep', points: 1, regions: ['farmland'], category: 'Animals' },
  { id: 'pig', emoji: '🐖', label: 'Pig', points: 1, regions: ['farmland'], category: 'Animals' },
  { id: 'chicken', emoji: '🐓', label: 'Chicken or rooster', points: 1, regions: ['farmland'], category: 'Animals' },
  { id: 'llama', emoji: '🦙', label: 'Llama or alpaca', points: 5, regions: ['farmland'], category: 'Animals', fact: 'Farmers sometimes keep llamas with sheep because llamas will chase off predators!' },
  { id: 'deer', emoji: '🦌', label: 'Deer', points: 3, regions: ['any', 'forest', 'mountains'], category: 'Animals' },
  { id: 'hawk-eagle', emoji: '🦅', label: 'Hawk or eagle', points: 3, regions: ['any'], category: 'Animals' },
  { id: 'squirrel', emoji: '🐿️', label: 'Squirrel', points: 1, regions: ['any'], category: 'Animals' },
  { id: 'owl', emoji: '🦉', label: 'Owl', points: 3, regions: ['forest'], category: 'Animals' },
  { id: 'wild-turkey', emoji: '🦃', label: 'Wild turkey', points: 3, regions: ['forest', 'farmland'], category: 'Animals' },
  { id: 'bear', emoji: '🐻', label: 'Bear (from a safe distance!)', points: 5, regions: ['mountains', 'forest'], category: 'Animals' },
  { id: 'mountain-goat', emoji: '🐐', label: 'Mountain goat on a cliff', points: 5, regions: ['mountains'], category: 'Animals' },
  { id: 'seagull', emoji: '🐦', label: 'Seagull', points: 1, regions: ['coastal'], category: 'Animals' },
  { id: 'turtle', emoji: '🐢', label: 'Turtle', points: 3, regions: ['any', 'coastal'], category: 'Animals' },
  { id: 'alligator', emoji: '🐊', label: 'Alligator (in the wild!)', points: 5, regions: ['coastal'], category: 'Animals' },
  { id: 'flamingo', emoji: '🦩', label: 'Flamingo', points: 5, regions: ['coastal'], category: 'Animals' },
  { id: 'scorpion', emoji: '🦂', label: 'Scorpion (statue, sign, or real!)', points: 5, regions: ['desert'], category: 'Animals' },
  { id: 'dog-window', emoji: '🐶', label: 'Dog with head out the window', points: 3, regions: ['any'], category: 'Animals' },

  // ---- Signs & Buildings ----
  { id: 'welcome-sign', emoji: '🪧', label: 'Welcome to [state] sign', points: 5, regions: ['any'], category: 'Signs & Buildings', fact: 'Every U.S. state has its own custom-designed welcome sign!' },
  { id: 'gas-station', emoji: '⛽', label: 'Gas station', points: 1, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'fast-food', emoji: '🍔', label: 'Fast food sign', points: 1, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'water-tower', emoji: '🗼', label: 'Water tower', points: 3, regions: ['any'], category: 'Signs & Buildings', fact: 'Some small towns paint fun logos or designs on their water towers.' },
  { id: 'drive-in-movie', emoji: '🎬', label: 'Drive-in movie theater', points: 5, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'covered-bridge', emoji: '🌉', label: 'Covered bridge', points: 5, regions: ['forest', 'mountains'], category: 'Signs & Buildings' },
  { id: 'billboard', emoji: '🖼️', label: 'Big billboard', points: 1, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'toll-booth', emoji: '💰', label: 'Toll booth', points: 3, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'rest-stop', emoji: '🚻', label: 'Rest stop / rest area', points: 1, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'barn', emoji: '🏡', label: 'Red barn', points: 1, regions: ['farmland'], category: 'Signs & Buildings' },
  { id: 'silo', emoji: '🌾', label: 'Grain silo', points: 1, regions: ['farmland'], category: 'Signs & Buildings' },
  { id: 'wind-turbine', emoji: '💨', label: 'Wind turbine', points: 3, regions: ['farmland', 'mountains'], category: 'Signs & Buildings' },
  { id: 'church-steeple', emoji: '⛪', label: 'Church with a steeple', points: 1, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'amusement-park', emoji: '🎢', label: 'Roller coaster / amusement park', points: 5, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'stadium', emoji: '🏟️', label: 'Sports stadium', points: 3, regions: ['urban'], category: 'Signs & Buildings' },
  { id: 'skyscraper', emoji: '🏙️', label: 'Skyscraper skyline', points: 1, regions: ['urban'], category: 'Signs & Buildings' },
  { id: 'mural', emoji: '🎨', label: 'Colorful mural or street art', points: 3, regions: ['urban'], category: 'Signs & Buildings' },
  { id: 'big-bridge', emoji: '🌁', label: 'Big bridge over water', points: 1, regions: ['any', 'coastal', 'urban'], category: 'Signs & Buildings' },
  { id: 'fruit-stand', emoji: '🍎', label: 'Fruit or veggie stand', points: 3, regions: ['farmland'], category: 'Signs & Buildings' },
  { id: 'casino', emoji: '🎰', label: 'Casino sign', points: 3, regions: ['any'], category: 'Signs & Buildings' },
  { id: 'park-sign', emoji: '🏞️', label: 'National or state park sign', points: 3, regions: ['mountains', 'forest', 'desert'], category: 'Signs & Buildings' },
  { id: 'lighthouse', emoji: '🏗️', label: 'Lighthouse', points: 5, regions: ['coastal'], category: 'Signs & Buildings' },

  // ---- Nature & Landscape ----
  { id: 'mountain-peak', emoji: '🏔️', label: 'Snow-capped mountain peak', points: 3, regions: ['mountains'], category: 'Nature' },
  { id: 'cactus', emoji: '🌵', label: 'Cactus', points: 1, regions: ['desert'], category: 'Nature' },
  { id: 'sand-dunes', emoji: '🏜️', label: 'Sand dunes', points: 3, regions: ['desert'], category: 'Nature' },
  { id: 'tumbleweed', emoji: '🌾', label: 'Tumbleweed', points: 5, regions: ['desert'], category: 'Nature' },
  { id: 'ocean-view', emoji: '🌊', label: 'Ocean view', points: 1, regions: ['coastal'], category: 'Nature' },
  { id: 'palm-tree', emoji: '🌴', label: 'Palm tree', points: 1, regions: ['coastal', 'desert'], category: 'Nature' },
  { id: 'beach', emoji: '🏖️', label: 'Sandy beach', points: 1, regions: ['coastal'], category: 'Nature' },
  { id: 'pier', emoji: '🎡', label: 'Pier or boardwalk', points: 3, regions: ['coastal'], category: 'Nature' },
  { id: 'waterfall', emoji: '💦', label: 'Waterfall', points: 5, regions: ['mountains', 'forest'], category: 'Nature' },
  { id: 'rainbow', emoji: '🌈', label: 'Rainbow', points: 5, regions: ['any'], category: 'Nature' },
  { id: 'river-lake', emoji: '💧', label: 'River or lake', points: 1, regions: ['any'], category: 'Nature' },
  { id: 'forest-trees', emoji: '🌲', label: 'Forest of tall trees', points: 1, regions: ['forest', 'mountains'], category: 'Nature' },
  { id: 'crop-field', emoji: '🌽', label: 'Field of crops', points: 1, regions: ['farmland'], category: 'Nature' },
  { id: 'hay-bale', emoji: '🟫', label: 'Round hay bale', points: 1, regions: ['farmland'], category: 'Nature' },
  { id: 'sunset', emoji: '🌅', label: 'Sunset', points: 1, regions: ['any'], category: 'Nature' },
  { id: 'fog', emoji: '🌫️', label: 'Fog rolling over hills', points: 3, regions: ['mountains', 'forest'], category: 'Nature' },

  // ---- Fun & Rare Finds ----
  { id: 'out-of-state-plate', emoji: '🚙', label: 'License plate from a faraway state', points: 3, regions: ['any'], category: 'Fun Finds', fact: 'See how many different states you can spot on license plates during the trip!' },
  { id: 'waving-driver', emoji: '👋', label: 'Another driver waving', points: 3, regions: ['any'], category: 'Fun Finds' },
  { id: 'jogger-biker', emoji: '🏃', label: 'Person jogging or biking', points: 1, regions: ['any'], category: 'Fun Finds' },
  { id: 'ice-cream-truck', emoji: '🍦', label: 'Ice cream truck or stand', points: 3, regions: ['any'], category: 'Fun Finds' },
  { id: 'fireworks-stand', emoji: '🎆', label: 'Fireworks stand', points: 3, regions: ['any'], category: 'Fun Finds' },
  { id: 'yard-sale', emoji: '🏷️', label: 'Yard sale sign', points: 1, regions: ['any'], category: 'Fun Finds' },
  { id: 'scarecrow', emoji: '🧑‍🌾', label: 'Scarecrow in a field', points: 3, regions: ['farmland'], category: 'Fun Finds' },
  { id: 'mailboxes', emoji: '📫', label: 'Row of mailboxes', points: 1, regions: ['any', 'farmland'], category: 'Fun Finds' },
  { id: 'state-line-sign', emoji: '🚧', label: 'Sign marking a state line', points: 3, regions: ['any'], category: 'Fun Finds' },
  { id: 'timezone-sign', emoji: '⏰', label: 'Time zone change sign', points: 5, regions: ['any'], category: 'Fun Finds' },
  { id: 'construction', emoji: '🚧', label: 'Construction zone with cones', points: 1, regions: ['any'], category: 'Fun Finds' },
  { id: 'crosswalk-crowd', emoji: '🚶', label: 'Crowded crosswalk', points: 1, regions: ['urban'], category: 'Fun Finds' },
];

const REGIONS = [
  { id: 'any', name: 'Mixed / Anywhere', emoji: '🗺️', description: 'A balanced mix of common road-trip sights, good for any route.' },
  { id: 'desert', name: 'Desert & Southwest', emoji: '🌵', description: 'Cactus, sand dunes, and wide-open desert highways.' },
  { id: 'coastal', name: 'Coastal & Beach', emoji: '🏖️', description: 'Ocean views, beaches, and boardwalks.' },
  { id: 'mountains', name: 'Mountains', emoji: '🏔️', description: 'Peaks, waterfalls, and winding mountain roads.' },
  { id: 'farmland', name: 'Farmland & Midwest', emoji: '🌾', description: 'Barns, crop fields, and farm animals.' },
  { id: 'forest', name: 'Forest & Pacific Northwest', emoji: '🌲', description: 'Tall trees, fog, and wildlife.' },
  { id: 'urban', name: 'Big City & Urban', emoji: '🏙️', description: 'Skylines, stadiums, and city street life.' },
];
